name : CI Workflow 
 
on:
  push:
    branches: ["main"]

  workflow_dispatch:  
   
env: 
  APP_DIRECTORY : ./src/myApp

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies 
        working-directory: $APP_DIRECTORY
        run: npm install

      - name: Build Angular project 
        working-directory: $APP_DIRECTORY
        run: npm run build:prod

      - name: Run tests 
        working-directory: $APP_DIRECTORY
        run: npm run test
         
      - name : Lint Code  
        working-directory: $APP_DIRECTORY
        run: npm run lint