name : CI Workflow 
 
on:
  push:
    branches: ["main"]

  workflow_dispatch:  
   
env: 
  APP_DIRECTORY : ./src/myApp

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies 
        working-directory: ./src/myApp
        run: npm install

      - name: Build Angular project 
        working-directory: ./src/myApp
        run: npm run build

      - name: Run tests 
        working-directory: ./src/myApp
        run: | 
          npm run test 
          ls  
          echo "LOL"
          cd coverage  
          ls  
          echo "LOL"
          cd my-app
         
      - name : Upload code coverage 
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./coverage/my-app/index.html

      - name : Lint Code  
        working-directory: ./src/myApp 
        run: npm run lint