name: Sphinx Wiki Deployment

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4 

    - name: Set up Python (Latest)
      uses: actions/setup-python@v4  
      with:
        python-version: "3.10"

    - name: Install dependencies (requirements.txt)
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt 

    - name: Build documentation
      run: |
        cd docs
        make html  
         
    - name: Upload build data
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-documentation
        path: ./docs/build/html  
   
  deploy: 
    needs : build 
    environment:
      name: documentation
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4 
    - name: Deploy Sphinx Wiki
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
       
