name: Automatic Wiki Generation & Deployment

on:
    push:
      branches: ["main"]
  
    workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies 
        working-directory: ./src/myApp
        run: npm install
      - name: Build doc 
        working-directory: ./src/myApp
        run: npm run doc
      - name: Upload build data 
        uses: actions/upload-artifact@v3 
        with:
          name: documentation 
          path: ./src/myApp/documentation 
  deploy:
    name : Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: documentation
          path: documentation
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages 
          FOLDER: documentation 
          CLEAN: true 